### ISSUE TITLE
Document prereqs / polyfills

### ISSUE THREAD

**Issue by matthewp** [matthewp/bram#34]
Custom elements, template tag, Maps, to start.

**Comment by LostInBrittany** [comment]
Have you tried to make it work with the different webcomponents polyfills?

Does it works avec the current stable of [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs) v0.7.23? Or with the [skatejs webcomponents polyfill[(https://github.com/skatejs/web-components)?

I guess the best way to know is to try... I'm going to do it :)

**Comment by matthewp** [comment]
It works with https://github.com/webcomponents/custom-elements, https://github.com/webcomponents/shadydom, and https://github.com/WebReflection/document-register-element. The Skate one is a combination of the above, so that should work too.

**Comment by LostInBrittany** [comment]
I've tried to make it work with the Skate polyfill, and it didn't work as intended.

![image](https://cloud.githubusercontent.com/assets/726476/21685333/7deac4c4-d361-11e6-9922-895deccca13f.png)

Without Polyfill it works nice on Chrome, and Firefox ignores the element (as it should, it hasn't Custom Element yet).

![image](https://cloud.githubusercontent.com/assets/726476/21685399/b74ab7ba-d361-11e6-83a8-e3e07cc805cc.png)

With Skate Polyfill, it kinda works... I mean, everything works besides the `<style>` inside the element:
![image](https://cloud.githubusercontent.com/assets/726476/21685552/45bdcdac-d362-11e6-8395-7ac3a5b62143.png)

Do you want me to submit a full issue for this?

**Comment by LostInBrittany** [comment]
Same thing (inner CSS style is ignored) when using directly [custom-elements]( https://github.com/webcomponents/custom-elements) and [shadydom](https://github.com/webcomponents/shadydom) polyfills. 

So I guessed that something CSS-related was missing, and guessing again I tried to add yet another polyfill to the mix: [shadycss](https://github.com/webcomponents/shadycss). But it didn’t work, the inner CSS was still unused.

I am sure I'm missing something, but I have no idea of what yet...

**Comment by LostInBrittany** [comment]
OK, I made it work by adding yet another polyfill to the mix:  [shadycss](https://github.com/webcomponents/shadycss). 

Some extra code lines are needed, in order to allow ShadyCSS to prepare the templates in browsers not supporting native shadow CSS:

```html
  <script>
    ShadyCSS.prepareTemplate(simpleElementTemplate, 'simple-element');
    class SimpleElement extends Bram.Element {
      static get template() {
        return '#simpleElementTemplate';
      }

      constructor() {
        super();
        ShadyCSS.applyStyle(this);
        this.model.count = 0;
      }


      handleClick() {
        this.model.count++;
      }
    }
    customElements.define('simple-element', SimpleElement);
  </script>
```

**Comment by matthewp** [comment]
Thanks @LostInBrittany, I'm currently working on guides and specifying the polyfills needed is part of that. You can see my progress in the guides branch: https://github.com/matthewp/bram/tree/guide/docs/doc

Will be sure to add the need for shadycss if using styles inside of shadow dom like that.

**Comment by LostInBrittany** [comment]
Thanks to you! As a big Polymer and webcomponents fan, I am thrilled to discover Bram.

I've just set-up a  repo with my tests, going to add some compatibility tests with Polymer and Skate: https://github.com/LostInBrittany/testing-bram

Please tell me if you need/want some help (with coding, doc, testing...), I'd be really happy to give a hand if needed/wanted.

**Comment by matthewp** [comment]
That test repo is awesome :)  Yeah, any contributions you want to make are more than welcome.  I'm giving a talk at the [Web Components Remote Conf](https://wcremoteconf.com/) next month, so most of my free time is going to be working on that for the next month or so. So updates to Bram will be less frequent.

But what I'm hoping is to finish off the guides so that Bram will be good enough for a 1.0 release. If there are parts of Bram that you don't understand, please file issues, or if you have ideas for docs that would be quite helpful too.

If you want to Watch this repo, I'll start adding some issues in the next few days about various things, please chime in if you have opinions or want to take something on. 😁

**Comment by LostInBrittany** [comment]
We are in the same ship, I'm also giving a talk at [Web Components Remote Conf](https://wcremoteconf.com/), we are even side by side on their speakers page :D 

![image](https://cloud.githubusercontent.com/assets/726476/21712168/5125e2ce-d3f3-11e6-822a-e95613b9dcea.png)


I'm watching this repo, and I'm going to continue my tests, reporting issues, giving opinions and, if I'm able, giving a hand on the eventual issues.

For the moment I really like what I've seen of Bram. Today after work I'm going to try to put Bram elements in one of my Polymer apps, I'll keep you informed :)

**Comment by matthewp** [comment]
Hah, I knew your avatar looked familiar from somewhere 🙃, best of luck on your talk!  Looking forward to hearing more from you about Bram.

**Comment by matthewp** [comment]
I added a page here: https://bramjs.org/compat.html

Since there's a lot of setup involved (as you experienced), I'm wondering if it would make sense to have a bundle, like `bram.all.js` perhaps, that includes all of the needed polyfills packed with Bram. What do you think?

**Comment by LostInBrittany** [comment]
It could be really nice for a Hello World or for discovering Bram, so I really agree :)

**Comment by matthewp** [comment]
Closing, never got around to this and now the polyfills are less necessary. I'll leave this to others to document.
