### ISSUE TITLE
JSBin umd version not updating list

### ISSUE THREAD

**Issue by roemhildtg** [matthewp/bram#50]
Just wanted to give this a quick test - http://jsbin.com/sexiqaveqe/edit?html,js,console,output

Not sure, am I missing something? Functionality seems to be there, but the list does not get created when I submit a todo.

**Comment by matthewp** [comment]
`each="{{todos}}"` works. I can't remember if I changed that intentionally or if it's a bug. I'm leaning towards bug, the curlies probably shouldn't be required here.

**Comment by matthewp** [comment]
In the new version based on template instantiation the curlies will be required because the underlying spec requires them.
